name: dtlTraders
main: net.dandielo.citizens.traders_v3.bukkit.DtlTraders
depend: [Citizens,Vault]
soft-depend: [Denizen,dtlWallets]
version: 3.0 Snapshot
description: >
             Citizens 2 trader and banker trait. 
commands:
  trader: 
    aliases: dtrader
    description: Dtl - CitizensTrader trader commands.
permissions:
  dtl.trader.commands.*:
    default: op
  dtl.trader.manage:
    default: op
  dtl.trader.use:
    default: true
  dtl.trader.sell:
    default: true
  dtl.trader.buy:
    default: true
