name: dtlTraders
main: net.dandielo.citizens.traders_v3.bukkit.DtlTraders
depend: [Citizens,Vault]
soft-depend: [Denizen,dtlWallets]
version: 3.0 Snapshot
description: >
             Citizens 2 trader and banker trait. 
