name: dtlTraders
main: net.dandielo.citizens.traders_v3.bukkit.DtlTraders
depend: [Citizens,Vault]
soft-depend: [Denizen,dtlStats]
version: 3.0.9-snapshot
description: >
             Citizens2 trader trait. 
commands:
  trader: 
    aliases: dtrader
    description: Dtl - Trader commands.
permissions:
  dtl.trader.default:
    default: true
    children:
      dtl.trader.use: true
      dtl.trader.buy: true
      dtl.trader.sell: true
  dtl.trader.*:
    default: op
    children:
      dtl.trader.use: true
      dtl.trader.buy: true
      dtl.trader.sell: true
      dtl.trader.manage: true
      dtl.trader.bypass.*: true
      dtl.trader.commands.*: true
  dtl.trader.commands.*:
    default: op
    children:
      dtl.trader.commands.open: true
      dtl.trader.commands.reset: true
      dtl.trader.commands.manage: true
      dtl.trader.commands.wallet: true
      dtl.trader.commands.create: true
      dtl.trader.commands.pattern: true
      dtl.trader.commands.buyprice: true
      dtl.trader.commands.stockname: true
      dtl.trader.commands.stocksize: true
      dtl.trader.commands.sellprice: true
      dtl.trader.commands.startstock: true
  dtl.trader.bypass.*:
    default: op
    children:
      dtl.trader.bypass.creative: true
